# Generated by Django 3.0.3 on 2020-03-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0005_framework_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('movies', models.ManyToManyField(to='example.Movie')),
            ],
        ),
    ]
